
GET http://localhost:3000/animals

###
GET http://localhost:3000/animals/1

###
POST http://localhost:3000/animals
Content-Type: application/json

{
  "species": "dinosaur",
  "age": 100
}
###

PATCH http://localhost:3000/animals/1
Content-Type: application/json

{
  "species": "The Doggy"
}